const orderActionTypes = {
  SELECT_ORDER_ADDRESS: "SELECT_ORDER_ADDRESS",
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",
  CLEAR_ORDER_STATE: "CLEAR_ORDER_STATE",
  FETCH_ORDER_START: "FETCH_ORDER_START",
  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_FAILURE: "FETCH_ORDER_FAILURE",
  FETCH_ORDER_BY_ID_START: "FETCH_ORDER_BY_ID_START",
  FETCH_ORDER_BY_ID_SUCCESS: "FETCH_ORDER_BY_ID_SUCCESS",
  FETCH_ORDER_BY_ID_FAILURE: "FETCH_ORDER_BY_ID_FAILURE",
  CLEAR_ORDER_BY_ID_LIST: "CLEAR_ORDER_BY_ID_LIST",
  FETCH_ORDER_BY_FIELD_START:"FETCH_ORDER_BY_FIELD_START",
  FETCH_ORDER_BY_FIELD_SUCCESS:"FETCH_ORDER_BY_FIELD_SUCCESS",
  FETCH_ORDER_BY_FIELD_FAILURE:"FETCH_ORDER_BY_FIELD_FAILURE",
  UPDATE_ORDER_BY_ID_START:'UPDATE_ORDER_BY_ID_START',
  UPDATE_ORDER_BY_ID_SUCCESS:'UPDATE_ORDER_BY_ID_SUCCESS',
  UPDATE_ORDER_BY_ID_FAILURE:'UPDATE_ORDER_BY_ID_FAILURE',
  FETCH_ORDER_STATS_START:'FETCH_ORDER_STATS_START',
  FETCH_ORDER_STATS_SUCCESS:'FETCH_ORDER_STATS_SUCCESS',
  FETCH_ORDER_STATS_FAILURE:'FETCH_ORDER_STATS_FAILURE'
};
export default orderActionTypes;
